param(
    [string]$RootDir = "rcm-platform"
)

$ErrorActionPreference = "Stop"

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host " RCM Platform Scaffolding Script" -ForegroundColor Cyan
Write-Host " Target: $((Get-Location).Path)\$RootDir" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

function New-Dir {
    param([string]$Path)
    $fullPath = Join-Path $RootDir $Path
    if (-not (Test-Path $fullPath)) {
        New-Item -ItemType Directory -Path $fullPath -Force | Out-Null
    }
}

function New-File {
    param([string]$Path)
    $fullPath = Join-Path $RootDir $Path
    $dir = Split-Path -Parent $fullPath
    if (-not (Test-Path $dir)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
    if (-not (Test-Path $fullPath)) {
        $ext = [System.IO.Path]::GetExtension($Path)
        $header = switch ($ext) {
            ".java"    { "// FILE: $Path`n// TODO: Generated by AI`n" }
            ".py"      { "# FILE: $Path`n# TODO: Generated by AI`n" }
            ".ts"      { "// FILE: $Path`n// TODO: Generated by AI`n" }
            ".tsx"     { "// FILE: $Path`n// TODO: Generated by AI`n" }
            ".js"      { "// FILE: $Path`n// TODO: Generated by AI`n" }
            ".gradle"  { "// FILE: $Path`n// TODO: Generated by AI`n" }
            ".yml"     { "# FILE: $Path`n# TODO: Generated by AI`n" }
            ".yaml"    { "# FILE: $Path`n# TODO: Generated by AI`n" }
            ".toml"    { "# FILE: $Path`n# TODO: Generated by AI`n" }
            ".sql"     { "-- FILE: $Path`n-- TODO: Generated by AI`n" }
            ".graphql" { "# FILE: $Path`n# TODO: Generated by AI`n" }
            ".proto"   { "// FILE: $Path`n// TODO: Generated by AI`n" }
            ".tf"      { "# FILE: $Path`n# TODO: Generated by AI`n" }
            ".json"    { "{}`n" }
            ".md"      { "# $([System.IO.Path]::GetFileNameWithoutExtension($Path))`n`n> TODO: Generated by AI`n" }
            ".hbs"     { "TODO: Generated by AI`n" }
            default    { "# FILE: $Path`n# TODO: Generated by AI`n" }
        }
        Set-Content -Path $fullPath -Value $header -Encoding UTF8
    }
}

Write-Host "`n[1/10] Root files..." -ForegroundColor Yellow
New-File "Makefile"
New-File "README.md"
New-File "CONTRIBUTING.md"
New-File "CHANGELOG.md"
New-File ".gitignore"
New-File ".gitattributes"
New-File ".editorconfig"
New-File ".pre-commit-config.yaml"
New-File "commitlint.config.js"
New-File "buf.yaml"

Write-Host "[2/10] GitHub workflows..." -ForegroundColor Yellow
New-File ".github/workflows/rcm-core-ci.yml"
New-File ".github/workflows/rcm-rag-ci.yml"
New-File ".github/workflows/rcm-notify-ci.yml"
New-File ".github/workflows/rcm-bff-ci.yml"
New-File ".github/workflows/rcm-ui-ci.yml"
New-File ".github/workflows/contract-tests.yml"
New-File ".github/PULL_REQUEST_TEMPLATE.md"
New-File ".github/ISSUE_TEMPLATE/bug_report.md"
New-File ".github/ISSUE_TEMPLATE/feature_request.md"
New-File ".github/CODEOWNERS"

Write-Host "[3/10] Docs and ADRs..." -ForegroundColor Yellow
$adrs = @(
    "ARCH-01-polyglot-topology","ARCH-02-modular-monolith","ARCH-03-protocol-choices",
    "ARCH-04-kafka-async-flows","ARCH-05-no-api-gateway","ARCH-06-multi-tenancy",
    "ARCH-07-resilience-patterns","ARCH-08-human-in-the-loop",
    "DATA-01-four-data-stores","DATA-02-pgvector-retrieval","DATA-03-cosmosdb-event-stream",
    "DATA-04-faiss-hot-cache","DATA-05-mongodb-audit-log","DATA-06-redis-cache",
    "DATA-07-caffeine-l1-cache","DATA-08-materialized-views","DATA-09-flyway-migrations",
    "DATA-10-embedding-model","DATA-11-llm-provider",
    "AI-01-llamaindex-langchain","AI-02-langgraph-agent","AI-03-phi-redaction",
    "AI-04-prompt-registry","AI-05-structured-outputs","AI-06-spring-ai",
    "AI-07-feature-flags","AI-08-eval-metrics","AI-09-semantic-cache","AI-10-token-budget",
    "SEC-01-oidc-keycloak","SEC-02-no-token-propagation","SEC-03-phi-encryption",
    "SEC-04-row-level-security","SEC-05-secrets-management","SEC-06-hipaa-audit-log",
    "SEC-07-input-validation",
    "OPS-01-observability-triad","OPS-02-lgtm-stack","OPS-03-testcontainers",
    "OPS-04-pact-contracts","OPS-05-github-actions","OPS-06-docker-compose",
    "OPS-07-feature-flags-ops"
)
foreach ($adr in $adrs) { New-File "docs/adr/$adr.md" }

$diagrams = @(
    "01-c4-system-context","02-c4-containers","03-c4-components-rcm-core",
    "04-c4-components-rcm-rag","05-c4-components-rcm-bff","06-c4-components-rcm-notify",
    "07-deployment-prod","08-deployment-local","09-network-trust-boundaries",
    "10-phi-data-flow","11-multi-tenancy","12-observability-topology",
    "13-agent-architecture","14-caching-architecture","15-prompt-registry",
    "16-erd-rcm-core","17-erd-rag-schema","18-cosmosdb-event-stream",
    "19-mongodb-audit-schema","20-uml-class-rcm-domain","21-uml-class-rag-domain",
    "22-uml-class-agent-domain","23-seq-eligibility-verification",
    "24-seq-claim-scrubbing-grpc","25-seq-claim-submission-kafka",
    "26-seq-denial-agent-async","27-seq-spring-ai-summarization",
    "28-seq-rag-eval-run","29-seq-rate-limit-enforcement",
    "30-state-claim-lifecycle","31-state-denial-lifecycle","32-state-agent-execution",
    "33-activity-biller-workflow","34-activity-claim-scrub-decision"
)
foreach ($d in $diagrams) { New-File "docs/diagrams/$d.md" }

$docPages = @(
    "architecture-overview.md","hipaa-security-guide.md","multi-tenancy-guide.md",
    "caching-strategy.md","ai-governance.md","prompt-engineering-guide.md",
    "eval-methodology.md","local-dev-setup.md","api-conventions.md",
    "rcm-glossary.md","INTERVIEW_PREP.md",
    "process/sprint-plan-template.md","process/retro-template.md",
    "process/code-review-checklist.md","process/pact-workflow.md"
)
foreach ($d in $docPages) { New-File "docs/$d" }

Write-Host "[4/10] Infrastructure..." -ForegroundColor Yellow
New-File "infrastructure/docker-compose.yml"
New-File "infrastructure/docker-compose.override.yml"
New-File "infrastructure/.env.example"
New-File "infrastructure/kafka/topics.yml"
New-File "infrastructure/kafka/schemas/claim-submitted.json"
New-File "infrastructure/kafka/schemas/denial-received.json"
New-File "infrastructure/kafka/schemas/denial-explained.json"
New-File "infrastructure/kafka/schemas/notification-requested.json"

$tfModules = @("networking","ecs","rds","elasticache","msk","cosmosdb")
foreach ($m in $tfModules) {
    New-File "infrastructure/terraform/modules/$m/main.tf"
    New-File "infrastructure/terraform/modules/$m/variables.tf"
}
New-File "infrastructure/terraform/main.tf"
New-File "infrastructure/terraform/variables.tf"
New-File "infrastructure/terraform/outputs.tf"
New-File "infrastructure/terraform/environments/dev.tfvars"
New-File "infrastructure/terraform/environments/prod.tfvars"

New-File "infrastructure/observability/prometheus/prometheus.yml"
New-File "infrastructure/observability/prometheus/alerts.yml"
New-File "infrastructure/observability/grafana/provisioning/datasources/datasources.yml"
New-File "infrastructure/observability/grafana/provisioning/dashboards/dashboards.yml"
$dashboards = @("service-overview","llm-cost","rag-quality","claim-throughput","agent-execution")
foreach ($d in $dashboards) {
    New-File "infrastructure/observability/grafana/dashboards/$d.json"
}
New-File "infrastructure/observability/loki/loki-config.yml"
New-File "infrastructure/observability/tempo/tempo-config.yml"
New-File "infrastructure/observability/mimir/mimir-config.yml"

$seedFiles = @(
    "synthetic-patients.sql","synthetic-payers.sql","cpt-codes.sql",
    "icd10-codes.sql","carc-codes.sql","rarc-codes.sql"
)
foreach ($s in $seedFiles) { New-File "infrastructure/seed-data/$s" }

$policies = @("aetna-policy-001","cigna-policy-001","uhc-policy-001","bcbs-policy-001")
foreach ($p in $policies) { New-File "infrastructure/seed-data/synthetic-payer-policies/$p.txt" }

$appeals = @("medical-necessity-appeal","coding-error-appeal","timely-filing-appeal")
foreach ($a in $appeals) { New-File "infrastructure/seed-data/synthetic-appeal-templates/$a.txt" }

Write-Host "[5/10] Proto..." -ForegroundColor Yellow
New-File "proto/rcm/v1/claim_scrubbing.proto"
New-File "proto/README.md"

Write-Host "[6/10] rcm-core (Java)..." -ForegroundColor Yellow
New-File "rcm-core/build.gradle"
New-File "rcm-core/settings.gradle"
New-File "rcm-core/Dockerfile"
New-File "rcm-core/.dockerignore"
New-File "rcm-core/checkstyle/checkstyle.xml"
New-File "rcm-core/spotless/java-format.xml"
New-File "rcm-core/gradle/wrapper/gradle-wrapper.properties"

$baseJ = "rcm-core/{0}/src/main/java/com/rcm/{1}"
$baseT = "rcm-core/{0}/src/test/java/com/rcm/{1}"

New-File "rcm-core/common/build.gradle"
$commonFiles = @(
    "config/SecurityConfig.java","config/JwtConfig.java","config/RedisConfig.java",
    "config/KafkaConfig.java","config/GrpcClientConfig.java","config/SpringAiConfig.java",
    "config/ObservabilityConfig.java",
    "domain/TenantId.java","domain/UserId.java","domain/Money.java",
    "multitenancy/TenantContext.java","multitenancy/TenantFilter.java",
    "multitenancy/TenantHibernateFilter.java",
    "security/JwtAuthFilter.java","security/InternalContextFilter.java","security/PhiAccess.java",
    "audit/AuditEvent.java","audit/AuditService.java","audit/AuditAspect.java",
    "cache/L1CacheConfig.java","cache/CacheInvalidationListener.java",
    "featureflags/FeatureFlag.java","featureflags/FeatureFlagService.java",
    "featureflags/FeatureFlagEntity.java",
    "events/DomainEvent.java","events/DomainEventPublisher.java",
    "exception/RcmException.java","exception/TenantIsolationException.java",
    "exception/GlobalExceptionHandler.java",
    "observability/MetricsConfig.java","observability/TraceConfig.java"
)
foreach ($f in $commonFiles) { New-File ($baseJ -f "common","common/$f") }
New-File ($baseT -f "common","common/multitenancy/TenantIsolationTest.java")
New-File ($baseT -f "common","common/audit/AuditAspectTest.java")

$contexts = @{
    "registration" = @(
        "domain/Patient.java","domain/PatientId.java","domain/Demographics.java","domain/InsuranceInfo.java",
        "repository/PatientRepository.java","service/PatientService.java",
        "api/PatientController.java","api/dto/CreatePatientRequest.java",
        "api/dto/PatientResponse.java","api/dto/UpdatePatientRequest.java",
        "api/mapper/PatientMapper.java","events/PatientRegisteredEvent.java"
    )
    "eligibility" = @(
        "domain/EligibilityRequest.java","domain/EligibilityResponse.java","domain/CoverageDetail.java",
        "domain/EligibilityResponseEntity.java",
        "repository/EligibilityResponseRepository.java",
        "service/EligibilityService.java","service/EligibilityCache.java",
        "client/PayerEligibilityClient.java",
        "api/EligibilityController.java",
        "api/dto/EligibilityCheckRequest.java","api/dto/EligibilityCheckResponse.java"
    )
    "charge-capture" = @(
        "domain/Encounter.java","domain/EncounterId.java","domain/ChargeItem.java",
        "domain/CptCode.java","domain/DiagnosisCode.java",
        "repository/EncounterRepository.java","repository/CptCodeRepository.java",
        "service/ChargeService.java",
        "api/ChargeController.java",
        "api/dto/CreateEncounterRequest.java","api/dto/EncounterResponse.java"
    )
    "claims" = @(
        "domain/Claim.java","domain/ClaimId.java","domain/ClaimLine.java",
        "domain/ClaimStatus.java","domain/ClaimScrubResult.java",
        "domain/Edi837.java","domain/ClaimSummary.java","domain/DenialInfo.java",
        "repository/ClaimRepository.java","repository/ClaimLineRepository.java",
        "service/ClaimService.java","service/ClaimScrubService.java",
        "service/ClaimSubmissionService.java","service/ClaimSummaryService.java",
        "service/Edi837Builder.java",
        "grpc/ClaimScrubGrpcClient.java",
        "kafka/ClaimEventPublisher.java",
        "cosmosdb/ClaimEventStreamClient.java",
        "api/ClaimController.java",
        "api/dto/CreateClaimRequest.java","api/dto/ClaimResponse.java",
        "api/dto/ScrubResultResponse.java","api/dto/SubmitClaimRequest.java"
    )
    "payments" = @(
        "domain/Payment.java","domain/PaymentId.java","domain/Era.java",
        "domain/EraLine.java","domain/Edi835Parser.java",
        "repository/PaymentRepository.java","repository/EraRepository.java",
        "service/PaymentPostingService.java",
        "api/PaymentController.java",
        "api/dto/PostPaymentRequest.java","api/dto/EraResponse.java"
    )
    "denials" = @(
        "domain/Denial.java","domain/DenialId.java","domain/DenialStatus.java",
        "domain/CarcCode.java","domain/RarcCode.java",
        "domain/AppealDraft.java","domain/AppealStatus.java",
        "repository/DenialRepository.java","repository/AppealRepository.java",
        "service/DenialService.java","service/AppealService.java",
        "service/RagApiClient.java",
        "kafka/DenialReceivedConsumer.java","kafka/DenialExplainedConsumer.java",
        "api/DenialController.java",
        "api/dto/DenialResponse.java","api/dto/AppealDraftResponse.java",
        "api/dto/ApproveAppealRequest.java"
    )
    "ar" = @(
        "domain/ArBalance.java","domain/AgingBucket.java",
        "repository/ArBalanceRepository.java",
        "service/ArService.java",
        "api/ArController.java","api/dto/ArAgingReport.java"
    )
}

foreach ($ctx in $contexts.Keys) {
    New-File "rcm-core/$ctx/build.gradle"
    $pkg = $ctx.Replace("-","")
    foreach ($f in $contexts[$ctx]) {
        New-File ($baseJ -f $ctx,"$pkg/$f")
    }
}

$testFiles = @{
    "registration" = @("registration/domain/PatientTest.java","registration/service/PatientServiceTest.java","registration/api/PatientControllerIntegrationTest.java")
    "eligibility"  = @("eligibility/service/EligibilityServiceTest.java","eligibility/api/EligibilityControllerIntegrationTest.java")
    "charge-capture" = @("chargecapture/service/ChargeServiceTest.java")
    "claims"       = @("claims/domain/ClaimTest.java","claims/service/ClaimServiceTest.java","claims/service/ClaimScrubServiceTest.java","claims/grpc/ClaimScrubGrpcClientTest.java","claims/api/ClaimControllerIntegrationTest.java")
    "payments"     = @("payments/service/PaymentPostingServiceTest.java")
    "denials"      = @("denials/domain/DenialTest.java","denials/service/DenialServiceTest.java")
    "ar"           = @("ar/service/ArServiceTest.java")
}
foreach ($ctx in $testFiles.Keys) {
    foreach ($f in $testFiles[$ctx]) { New-File ($baseT -f $ctx,$f) }
}

New-File "rcm-core/app/build.gradle"
New-File "rcm-core/app/src/main/java/com/rcm/RcmCoreApplication.java"
New-File "rcm-core/app/src/main/resources/application.yml"
New-File "rcm-core/app/src/main/resources/application-dev.yml"
New-File "rcm-core/app/src/main/resources/application-test.yml"
New-File "rcm-core/app/src/main/resources/application-prod.yml"
New-File "rcm-core/app/src/main/resources/logback-spring.xml"
New-File "rcm-core/app/src/test/java/com/rcm/RcmCoreApplicationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/AbstractIntegrationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/ClaimScrubFlowIntegrationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/DenialKafkaFlowIntegrationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/EligibilityCacheFlowIntegrationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/ClaimFullLifecycleIntegrationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/MultiTenantSecurityIntegrationTest.java"
New-File "rcm-core/app/src/test/java/com/rcm/pact/RcmCorePactProviderTest.java"
New-File "rcm-core/app/src/test/resources/application-test.yml"

$migrations = @(
    "V001__create_extensions.sql","V002__create_tenants.sql","V003__create_patients.sql",
    "V004__create_encounters.sql","V005__create_claims.sql","V006__create_claim_lines.sql",
    "V007__create_payers.sql","V008__create_payments.sql","V009__create_eras.sql",
    "V010__create_denials.sql","V011__create_appeals.sql","V012__create_ar_balances.sql",
    "V013__create_feature_flags.sql","V014__create_rag_schema.sql",
    "V015__create_vector_indexes.sql","V016__create_materialized_views.sql"
)
foreach ($m in $migrations) { New-File "rcm-core/app/src/main/resources/db/migration/$m" }

Write-Host "[7/10] rcm-rag (Python)..." -ForegroundColor Yellow
New-File "rcm-rag/pyproject.toml"
New-File "rcm-rag/Dockerfile"
New-File "rcm-rag/.dockerignore"
New-File "rcm-rag/ruff.toml"
New-File "rcm-rag/mypy.ini"
New-File "rcm-rag/.pre-commit-config.yaml"

$ragPkg = "rcm-rag/rcm_rag"
New-File "$ragPkg/__init__.py"
New-File "$ragPkg/main.py"
New-File "$ragPkg/config.py"

$ragFiles = @(
    "common/__init__.py","common/auth.py","common/multitenancy.py","common/audit.py",
    "common/phi_redactor.py","common/observability.py","common/feature_flags.py","common/exceptions.py",
    "db/__init__.py","db/postgres.py","db/redis_client.py","db/mongo_client.py","db/cosmosdb_client.py",
    "ingestion/__init__.py","ingestion/document_loader.py","ingestion/chunker.py",
    "ingestion/embedder.py","ingestion/pgvector_store.py","ingestion/faiss_cache.py",
    "ingestion/ingestion_pipeline.py",
    "retrieval/__init__.py","retrieval/retriever.py","retrieval/semantic_cache.py","retrieval/reranker.py",
    "prompts/__init__.py","prompts/registry.py",
    "prompts/claim-scrubbing-v1.0.0.yaml","prompts/denial-explanation-v1.0.0.yaml",
    "prompts/appeal-drafting-v1.0.0.yaml","prompts/medical-necessity-v1.0.0.yaml",
    "llm/__init__.py","llm/client.py","llm/azure_openai_client.py","llm/ollama_client.py",
    "llm/structured_output.py","llm/token_counter.py",
    "llm/middleware/__init__.py","llm/middleware/budget_middleware.py",
    "llm/middleware/rate_limit_middleware.py","llm/middleware/token_counting_middleware.py",
    "agent/__init__.py","agent/graph.py","agent/state.py","agent/persistence.py",
    "agent/nodes/__init__.py","agent/nodes/triage.py","agent/nodes/lookup_carc.py",
    "agent/nodes/fetch_payer_policy.py","agent/nodes/check_medical_necessity.py",
    "agent/nodes/draft_appeal.py","agent/nodes/human_review.py","agent/nodes/finalize.py",
    "agent/tools/__init__.py","agent/tools/carc_lookup_tool.py","agent/tools/payer_policy_tool.py",
    "agent/tools/medical_necessity_tool.py","agent/tools/appeal_draft_tool.py",
    "flows/__init__.py","flows/claim_scrubbing.py","flows/denial_explanation.py",
    "grpc/__init__.py","grpc/claim_scrub_servicer.py",
    "kafka/__init__.py","kafka/consumer.py","kafka/producer.py",
    "schemas/__init__.py","schemas/scrub_result.py","schemas/denial_explanation.py",
    "schemas/appeal_draft.py","schemas/agent_state.py","schemas/medical_necessity.py",
    "api/__init__.py","api/router.py","api/health.py","api/ingestion.py",
    "api/retrieval.py","api/denial.py","api/eval.py","api/pact_states.py"
)
foreach ($f in $ragFiles) { New-File "$ragPkg/$f" }

$evalFiles = @(
    "__init__.py","runner.py",
    "metrics/__init__.py","metrics/retrieval_metrics.py","metrics/generation_metrics.py",
    "metrics/domain_metrics.py","metrics/operational_metrics.py",
    "golden_sets/claim_scrubbing_golden.json","golden_sets/denial_explanation_golden.json",
    "thresholds.yaml"
)
foreach ($f in $evalFiles) { New-File "rcm-rag/evals/$f" }
New-Dir "rcm-rag/evals/reports"

$ragTestFiles = @(
    "conftest.py",
    "unit/test_phi_redactor.py","unit/test_chunker.py","unit/test_retriever.py",
    "unit/test_structured_output.py","unit/test_prompt_registry.py",
    "unit/test_token_counter.py","unit/test_agent_graph.py",
    "integration/test_ingestion_pipeline.py","integration/test_claim_scrubbing_grpc.py",
    "integration/test_denial_kafka_flow.py","integration/test_semantic_cache.py",
    "integration/test_full_rag_pipeline.py","integration/test_agent_interrupt_resume.py",
    "integration/test_phi_redaction_in_pipeline.py","integration/test_semantic_cache_threshold.py",
    "pact/test_pact_provider.py"
)
foreach ($f in $ragTestFiles) { New-File "rcm-rag/tests/$f" }

New-File "rcm-rag/scripts/ingest_corpus.py"
New-File "rcm-rag/scripts/rebuild_faiss_index.py"

Write-Host "[8/10] rcm-notify (Node.js)..." -ForegroundColor Yellow
New-File "rcm-notify/package.json"
New-File "rcm-notify/tsconfig.json"
New-File "rcm-notify/Dockerfile"
New-File "rcm-notify/.dockerignore"
New-File "rcm-notify/.eslintrc.json"

$notifySrc = @(
    "index.ts","config.ts",
    "common/auth.ts","common/multitenancy.ts","common/audit.ts",
    "common/observability.ts","common/errors.ts",
    "kafka/consumer.ts",
    "kafka/handlers/claimSubmittedHandler.ts",
    "kafka/handlers/denialReceivedHandler.ts",
    "kafka/handlers/denialExplainedHandler.ts",
    "channels/email.ts","channels/sms.ts","channels/webhook.ts",
    "templates/claim-submitted.hbs","templates/denial-received.hbs",
    "templates/appeal-ready-for-review.hbs",
    "db/postgres.ts","api/router.ts","api/health.ts"
)
foreach ($f in $notifySrc) { New-File "rcm-notify/src/$f" }
New-File "rcm-notify/tests/unit/channels.test.ts"
New-File "rcm-notify/tests/unit/handlers.test.ts"
New-File "rcm-notify/tests/integration/kafka.integration.test.ts"

Write-Host "[9/10] rcm-bff (Node.js/GraphQL)..." -ForegroundColor Yellow
New-File "rcm-bff/package.json"
New-File "rcm-bff/tsconfig.json"
New-File "rcm-bff/Dockerfile"
New-File "rcm-bff/.dockerignore"
New-File "rcm-bff/.eslintrc.json"

$bffSrc = @(
    "index.ts","config.ts",
    "common/auth.ts","common/multitenancy.ts","common/observability.ts",
    "common/context.ts","common/dataloader.ts","common/errors.ts",
    "schema/typeDefs/patient.graphql","schema/typeDefs/claim.graphql",
    "schema/typeDefs/denial.graphql","schema/typeDefs/payment.graphql",
    "schema/typeDefs/ar.graphql","schema/typeDefs/agent.graphql",
    "schema/index.ts",
    "resolvers/patient.resolver.ts","resolvers/claim.resolver.ts",
    "resolvers/denial.resolver.ts","resolvers/payment.resolver.ts",
    "resolvers/ar.resolver.ts","resolvers/agent.resolver.ts","resolvers/index.ts",
    "dataSources/RcmCoreApi.ts","dataSources/RcmRagApi.ts",
    "db/postgres.ts","api/router.ts","api/health.ts","api/sse.ts"
)
foreach ($f in $bffSrc) { New-File "rcm-bff/src/$f" }
New-File "rcm-bff/tests/unit/resolvers.test.ts"
New-File "rcm-bff/tests/integration/graphql.integration.test.ts"
New-File "rcm-bff/tests/pact/rcm-core.pact.test.ts"

Write-Host "[10/10] rcm-ui (Next.js)..." -ForegroundColor Yellow
New-File "rcm-ui/package.json"
New-File "rcm-ui/tsconfig.json"
New-File "rcm-ui/next.config.ts"
New-File "rcm-ui/tailwind.config.ts"
New-File "rcm-ui/Dockerfile"
New-File "rcm-ui/.dockerignore"
New-File "rcm-ui/.eslintrc.json"

$uiFiles = @(
    "app/layout.tsx","app/page.tsx","app/providers.tsx",
    "app/(auth)/login/page.tsx","app/(auth)/callback/page.tsx",
    "app/claims/page.tsx","app/claims/[claimId]/page.tsx",
    "app/denials/page.tsx","app/denials/[denialId]/page.tsx",
    "components/claims/ClaimsDashboard.tsx","components/claims/ClaimStatusBadge.tsx",
    "components/claims/ClaimCard.tsx",
    "components/denials/DenialQueue.tsx","components/denials/DenialReviewPanel.tsx",
    "components/denials/AppealDraftEditor.tsx","components/denials/AgentStepsTimeline.tsx",
    "components/shared/LoadingSpinner.tsx","components/shared/ErrorBoundary.tsx",
    "components/shared/TenantHeader.tsx",
    "lib/auth.ts","lib/graphql-client.ts","lib/sse-client.ts","lib/api.ts",
    "queries/claims.graphql","queries/denials.graphql",
    "tests/unit/components/AppealDraftEditor.test.tsx",
    "tests/e2e/playwright.config.ts",
    "tests/e2e/claims-dashboard.spec.ts","tests/e2e/denial-review.spec.ts"
)
foreach ($f in $uiFiles) { New-File "rcm-ui/$f" }

Write-Host "`nInitialising git..." -ForegroundColor Yellow
Set-Location $RootDir
git init | Out-Null
git add . | Out-Null
git commit -m "chore: scaffold empty project structure" | Out-Null
Set-Location ..

$fileCount = (Get-ChildItem -Recurse -File -Path $RootDir).Count
$dirCount  = (Get-ChildItem -Recurse -Directory -Path $RootDir).Count

Write-Host "`n==========================================" -ForegroundColor Green
Write-Host " Scaffolding complete!" -ForegroundColor Green
Write-Host " Directories : $dirCount" -ForegroundColor Green
Write-Host " Files       : $fileCount" -ForegroundColor Green
Write-Host " Location    : $((Get-Location).Path)\$RootDir" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Green
Write-Host "`nNext step: .\05_VERIFY_SCAFFOLD.ps1" -ForegroundColor Cyan
